version: "3.7"
services:
  oauth2proxy:
    image: "bitnami/oauth2-proxy:latest"
    ports:
    - "8080:8080"
    command: [
      "--provider=github",
      "--github-user=payne,ex1payne",
      "--cookie-secure=false",
      "--upstream=http://fava:5000",
      "--http-address=0.0.0.0:8080",
      "--skip-auth-regex=/forms/*",
      "--redirect-url=http://cs-mcc.org:8080/oauth2/callback",
      "--email-domain=*"
    ]
    env_file:
      - .env  
  fava:
    image: yegle/fava
    volumes: 
    - ./data:/data/
    environment:
      BEANCOUNT_FILE: /data/fava.bean

